### ISSUE TITLE
embedd dashboard

### ISSUE THREAD

**Issue by pjkreutzer** [swinnoproject/website#1]
Quarto is a static website generator and hosting on gh pages allows only static pages.
But the people at posit have build and extension to embedd shiny components into quarto documents [shinylive](https://quarto.org/docs/blog/posts/2022-10-25-shinylive-extension/).

I do not know how easy it will be to style the components, or how computations are handled, but the documentation for quarto is usually quite good.

So while embedding the dashboard, or at least components seems possible in theory, I wonder how useful it will be in reality.
Perhaps having a dedicated dashboard, linking to it and only using some of its components as teasers, would be a better approach?

In the example from VTT, they use simply screen shots of their dashboard, with no interactivity.

@MatJohaDH

**Comment by pjkreutzer** [comment]
In quarto 1.4 extensive support for dashboards is added. https://quarto.org/docs/dashboards/
Currently on pre-release version

**Comment by mathjoha** [comment]
As of c74514187be3b4c28b5b1795b986e6fbb97b4623 the WIP dashboard is built with ObservableJS wihtin Quarto's `dadhboard` page-type. 
This JavaScript-based version loads the export-database from Zenodo and runs all calculations behind the visualistions iin the user's browser -- which is a lot more interactive.
The older WIP dashboard was build with python to pre-calculate plots, and was therefore a lot less interactive.
