### ISSUE TITLE
"Site not found"

### ISSUE THREAD

**Issue by MatJohaDH** [swinnoproject/website#11]
Tried to access the [site](https://swinnoproject.github.io/website/) @ 2023-11-09T11:30 and is met with a 404 error.

The deployment ran without issues and I can render it locally in WSL as is.

Assigning it to our resident Quarto-wizard (Quizard if you will) @pjkreutzer.

**Comment by pjkreutzer** [comment]
Not a bug, but intended. Unpublished according to Josef's request to not have it visible while under construction.

**Comment by MatJohaDH** [comment]
@pjkreutzer
