### ISSUE TITLE
set up custom domain

### ISSUE THREAD

**Issue by pjkreutzer** [swinnoproject/website#15]
When ever you are ready @MatJohaDH . I sadly have little experience with this, but the documentation looked straight forward enough. We could also consider hosting the site on netlify instead of gh pages, although that might be overkill.

**Comment by MatJohaDH** [comment]
@pjkreutzer 
I added the custom domain in the settings yesterday, and it seems to be redirected correctly to gh-pages...
However, a bit difficult to verify when the page is not set to be shown yet -- or have you changed that setting?
